### ISSUE TITLE
Table Selection based on number of Guests

### ISSUE THREAD

**Issue by Paul-lol** [Paul-lol/SE-Project#37]
Dynamic dropbox that changed depending on the number of guests.

**Comment by jvergara24** [comment]
initial idea - separate reservation form to two pages ( {Name, Phone #, Email, Date, Time, and Number of Guests} on page 1 then {Table selection (dynamic dropdown), Tables Image} on page 2 )

**Comment by jvergara24** [comment]
1. create initial reservation after page 1 (save to db) with flag for wasFinalized (page 1 + 2 completed and saved as complete reservation)
2. On page 2, find initial reservation
3. Use input date, time, and guests to dynamically set the tables dropdown
4. combine initial reservation with selected table and save to database as a complete reservation
5. delete initial reservation

- To clean bloat from unfinished reservations (user exits after page 1), delete all documents in the initial reservations collection on server start (or when user leaves reservation page 1 for a page other than reservation page 2)
